### ISSUE TITLE
Remove YAML config file, replace with CLI parameters

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-icon-upload#43]
**Is your feature request related to a problem? Please describe.**
It doesn't really make sense to have both a config file and command line parameters.

Move the few settings in the config file to CLI parameters instead.
This will be a breaking change.

The config file settings are

```yaml
iconUploader:
  # Possible log levels are silly, debug, verbose, info, warn, error
  logLevel: info

  # Info needed to connect to the repository service (QRS)
  qrs:
    host: <Sense host where QRS is running>
    clientCertPath: /path/to/client/certificate/client.pem
    clientCertKeyPath: /path/to/client/certificate/client_key.pem
```
